name: Generate Pac-Man Game

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Colorful Pac-Man
        uses: Platane/snk@v3
        with:
          github_user_name: SaurabhM2410
          outputs: |
            dist/pacman.svg?color_snake=yellow&color_dots=#ff6b6b,#4ecdc4,#45b7d1,#96ceb4,#feca57
            dist/pacman-dark.svg?palette=github-dark&color_snake=yellow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
